-- Migration 006: Report definitions, scheduled runs, metric snapshots,
-- export jobs, and watermark rules.
--
-- Version comparison: two report_runs for the same report_id can be compared
-- by joining their report_snapshots on metric_name and computing delta values.
-- version_label is auto-generated by ReportService as "<report_type>-<YYYYMMDD>-<run_seq>".

CREATE TABLE IF NOT EXISTS report_definitions (
    report_id       INTEGER PRIMARY KEY,
    name            TEXT    NOT NULL,
    report_type     TEXT    NOT NULL CHECK(report_type IN (
                        'occupancy','turnover','maintenance_response',
                        'overdue_fees','inventory_summary','audit_export','custom'
                    )),
    description     TEXT,
    -- Default filter JSON; overridden at run time
    filter_json     TEXT    NOT NULL DEFAULT '{}',
    -- NULL = on-demand only; set for scheduled reports
    schedule_cron   TEXT,
    is_active       INTEGER NOT NULL DEFAULT 1,
    created_by      INTEGER REFERENCES users(user_id),
    created_at      INTEGER NOT NULL    -- IMMUTABLE
);

CREATE INDEX IF NOT EXISTS idx_reports_type ON report_definitions(report_type);

CREATE TABLE IF NOT EXISTS report_runs (
    run_id          INTEGER PRIMARY KEY,
    report_id       INTEGER NOT NULL REFERENCES report_definitions(report_id),
    -- e.g. "occupancy-20260420-003"; used to identify runs in version comparison
    version_label   TEXT    NOT NULL,
    triggered_by    INTEGER REFERENCES users(user_id),
    trigger_type    TEXT    NOT NULL CHECK(trigger_type IN ('manual','scheduled','api')),
    started_at      INTEGER NOT NULL,
    completed_at    INTEGER,
    status          TEXT    NOT NULL DEFAULT 'queued' CHECK(status IN (
                        'queued','running','completed','failed','cancelled'
                    )),
    -- Filter snapshot: preserves exact filter state at run time for reproducibility
    filter_json     TEXT    NOT NULL DEFAULT '{}',
    output_path     TEXT,
    error_message   TEXT,
    -- JSON array of anomaly/failure descriptions surfaced in-app
    anomaly_flags_json TEXT,
    row_count       INTEGER
);

CREATE INDEX IF NOT EXISTS idx_runs_report      ON report_runs(report_id);
CREATE INDEX IF NOT EXISTS idx_runs_status      ON report_runs(status);
CREATE INDEX IF NOT EXISTS idx_runs_started     ON report_runs(started_at);
-- Used for version comparison: find prior run of same report
CREATE INDEX IF NOT EXISTS idx_runs_version     ON report_runs(report_id, started_at);

-- Per-metric values captured at run completion; basis for version delta computation.
-- dimension_json: {"zone":"Building A","pet_type":"dog","staff_id":7,"period":"2026-Q1"}
CREATE TABLE IF NOT EXISTS report_snapshots (
    snapshot_id     INTEGER PRIMARY KEY,
    run_id          INTEGER NOT NULL REFERENCES report_runs(run_id),
    metric_name     TEXT    NOT NULL,
    metric_value    REAL    NOT NULL,
    dimension_json  TEXT    NOT NULL DEFAULT '{}',
    captured_at     INTEGER NOT NULL    -- IMMUTABLE
);

CREATE INDEX IF NOT EXISTS idx_snapshots_run    ON report_snapshots(run_id);
CREATE INDEX IF NOT EXISTS idx_snapshots_metric ON report_snapshots(metric_name);

-- Export jobs: one per requested export format for a completed report_run.
-- max_concurrency = 1 for PDF; throttled via JobQueue to prevent UI freeze.
CREATE TABLE IF NOT EXISTS export_jobs (
    job_id          INTEGER PRIMARY KEY,
    report_run_id   INTEGER NOT NULL REFERENCES report_runs(run_id),
    format          TEXT    NOT NULL CHECK(format IN ('csv','pdf')),
    requested_by    INTEGER NOT NULL REFERENCES users(user_id),
    queued_at       INTEGER NOT NULL,
    started_at      INTEGER,
    completed_at    INTEGER,
    output_path     TEXT,
    status          TEXT    NOT NULL DEFAULT 'queued' CHECK(status IN (
                        'queued','running','completed','failed','cancelled'
                    )),
    max_concurrency INTEGER NOT NULL DEFAULT 1 CHECK(max_concurrency > 0)
);

CREATE INDEX IF NOT EXISTS idx_export_status ON export_jobs(status);
CREATE INDEX IF NOT EXISTS idx_export_run    ON export_jobs(report_run_id);
CREATE INDEX IF NOT EXISTS idx_export_user   ON export_jobs(requested_by);

-- Watermark and download restriction rules by (report_type, role, format).
CREATE TABLE IF NOT EXISTS watermark_rules (
    rule_id             INTEGER PRIMARY KEY,
    report_type         TEXT    NOT NULL,
    role                TEXT    NOT NULL,
    export_format       TEXT    NOT NULL,
    requires_watermark  INTEGER NOT NULL DEFAULT 0,
    restrictions_json   TEXT    NOT NULL DEFAULT '{}',
    UNIQUE(report_type, role, export_format)
);
